name: Create tag version

# Lucid openapi validator version is synced with the version of the IBM openapi
# validator that it wraps. Therefore the version can be sniffed from the
# dockerfile and used to create a tag when master is pushed.

# NOTE: this will fail when a tag already exists, but nothing bad happens as a
# side effect. However, master can end up with an annoying red x.

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jaliborc/action-general-autotag@1.0.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "Dockerfile"
        extraction_regex: ":(v\\d+\\.\\d+\\.\\d+)"
